### ISSUE TITLE
Not Working on Ubuntu 22.04

### ISSUE THREAD

**Issue by Kapyyyy** [NOXCIS/Worm-Hole#11]
First of all I'm pretty inexperienced with linux etc so I'm sorry if this is somehow my fault :/

Here's what I did

First I installed docker and I set it up to run as root.

Then I installed Worm-hole using the install.sh script (in auto mode, but I also tried manual) on an oracle vps running [Canonical-Ubuntu-22.04-2023.06.30-0] on x64 cpu

Checking with docker ps looks like this https://i.imgur.com/XxifEd8.png
and checking trough portainer (which I'm slightly more familiar with compared to interacting with docker trough the cli) for the container logs on the wg_dashboard container shows it generating new master keys once a minute, but there's no errors or anything extra being printed https://imgur.com/a/UQUMpnM

I also tried to set this up trough portainers custom templates using the compose.yml and ran into the same issue

any solution to get this running would be nice and I can provide more info if necessary

**Comment by NOXCIS** [comment]
Which release are you using

**Comment by NOXCIS** [comment]
Might use a release. I test in prod sometimes. Also if using a release modify the compose to build instead of pulling the image.

**Comment by Kapyyyy** [comment]
I deleted all the containers and images I had as well as the worm-hole folder, Re-installed using the commands in the instructions, but before runnign the install script I opened up the docker-compose file and un-commented the with "build: ./WG-Dash" which is what I'm assuming you were telling me to do, but the end result is still the same, the wg-dashboard keeps restarting every minute just like before.

**Comment by NOXCIS** [comment]
Did you do a docker compose down before removing the worm-hole folder?

**Comment by NOXCIS** [comment]
Also, try this:
```bash
- cd Worm_Hole
- docker compose down
- cd ..
- rm -r  Worm-Hole
- git clone https://github.com/NOXCIS/Worm-Hole.git
- cd Worm-Hole
- sudo chmod +x ./install.sh
- sudo ./install.sh 
- Reset Wireguard
- Auto Install Option 2
- 
```

**Comment by Kapyyyy** [comment]
1. I used portainer to stop and remove the containers and the downloaded docker images, since I'm not that familiar with using docker trough the terminal

2. I followed your new instructions and I'm still stuck with the same issue as before
I also tried the new instructions + uncommenting the build line to see if that would make a difference, but no

**Comment by NOXCIS** [comment]
Can you attach your logs.

**Comment by Kapyyyy** [comment]
How would I go about doing that?

**Comment by NOXCIS** [comment]
docker ps 
Get the container ID of wg-dashboard 
docker logs <container ID>

**Comment by Kapyyyy** [comment]
Like I said in the original post, the wg-dashboard just keeps printing new qr codes and keys once a minute with nothing in between the sets of keys and qr codes

https://imgur.com/a/UQUMpnM

**Comment by NOXCIS** [comment]
What are you running it on

**Comment by Kapyyyy** [comment]
from my original post "on an oracle vps running [Canonical-Ubuntu-22.04-2023.06.30-0] on x64 cpu"

**Comment by NOXCIS** [comment]
Fixed
