### ISSUE TITLE
Just question on DNS leak test

### ISSUE THREAD

**Issue by nishp77** [NOXCIS/Worm-Hole#12]
I saw that there's change in unbund config, having a custom one. So I performed a DNS leak test, I though should it be not your public IP?

![image](https://github.com/NOXCIS/Worm-Hole/assets/35785259/41076fa0-98be-4c87-8b90-2c24c388781e)

**Comment by nishp77** [comment]
When I was using very old version it was showing my public IP address?

**Comment by NOXCIS** [comment]
It's an optional forward zone. Everything still good it just tells unbound to only use cloud flare. Notice how the DNS server responses still match the geographic location of the VPS.

Unbound-Custom-Config/unbound.conf
![image](https://github.com/NOXCIS/Worm-Hole/assets/26854391/0e3d4d74-95f8-4921-9967-ca77b966b789)

**Comment by NOXCIS** [comment]
It's like queries still happen server side because of the wormhole private network. It just nice to have to prevent bound from going to googles house cause it's the closest.
