### ISSUE TITLE
AdguardHome as an option?

### ISSUE THREAD

**Issue by PDXUser** [NOXCIS/Worm-Hole#18]
We are AdguardHome users and I use their DHCP Server and have it pre-configured for everythign already, and found that to fit our needs more specifically.  Would you be willing to make that an option in lieu of PiHole?

**Comment by NOXCIS** [comment]
- Ill add it to the next release
- also looking for help with this project

**Comment by NOXCIS** [comment]
@PDXUser In 8 hours adguard is an install option

**Comment by PDXUser** [comment]
Great!  I installed the pihole version last night and have some feedback to help make the onboarding process easier for users.  For this test, I ran it using the Express install option.

On my Raspberry Pi4 where I installed it, I didn't have Docker installed, so I had to do that, but it wasn't as simple as just running an apt get command.   Instead, I had to run the following to get it to install first:

```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```
Running those brought Docker in, then the script ran without complaints.   So perhaps adding a check for Docker first before moving through the process and then installing it as an option would be ideal.  

On top of this, I got it to install and aside from it not being able to resolve my host name (Easily fixed by mapping it in my /etc/hosts file), it spit out my credentials. 

An opinionated suggestion I have so far, is not mandating the connection to Wireguard before management of the Pihole and other interfaces is preferable at least for me.    Other projects like Mistborn do this and I found that connecting to Wireguard just to manage my services while sitting in the same room as the server, doesn't make any sense.   Not to mention the fact that like other folks, I work from home, and at least my connection to my work's VPN is hypersensitive.  Any change of connection greater than 1 second, and it freezes my connection to there.  So, if for example, family needs to have something adjusted, and I'm at work, I can't just toggle to my browser's window to make those adjustments to unblock maybe a site which we know is littered with Ads, but they insist on it! :)   One can argue that this is really meant to be placed on the cloud and therefore Wireguard is recommended to manage this and I 100% agree, so having the option to not require Wireguard to manage the services IMHO would be a plus!  

With that out of the way, connecting to the tunnel inside my network from within my network (whee!!!)  Was a piece of cake, with my Arch Desktop system using KDE's network manager.    So, I was able to at least access the login pages to both GUI's (Pihole and WG Dashboard a.k.a. http://worm.hole  ) 

Another point of confusion on my end, and maybe it's just the lack of coffee this morning (It's 5 am West Coast time lol)  but I got confused with the credentials for http://worm.hole.   I had to go back to your readme.md to see it was the admin/admin and not  admin and the "MASTER KEY DECRYPTION KEY"  which at this point, I'm not too sure what that's about.  Again, it's early yet.    Maybe adding that to the output text for the login for this service after install would be a nice touch. 

How about the option too to dump the credentials to a .txt file or whatnot locally after the install is complete so the user can save that elsewhere or refer to it easily?  Yeah - storing plain text on a server with credentials is bad, so maybe something else.  

**SPEED ISSUES**

Now, I can attribute this to my installation system being a Rpi4 and WIRELESS, but while connected to it in Wireguard, my network is very slow:

![image](https://github.com/NOXCIS/Worm-Hole/assets/20736534/be5fe7a6-5755-4abe-ada6-17465507a041)

VS. Not connecting it to my Wireguard tunnel:

![image](https://github.com/NOXCIS/Worm-Hole/assets/20736534/454340c7-250e-4516-8eab-0255630b4dec)

Certainly, installing this on a wired LAN server or in the cloud won't present this issue but I figured I would bring this out as well just in case you have other users deploying this and then they find their speeds to be less than stellar.  :)

I run Proxmox on my primary server which I look forward to testing your install later tonight with AdguardHome and can report back on that.  (That's a wired LAN setup so I can count on better speeds).

**Comment by NOXCIS** [comment]
Adguard install is live.
- Worm-Hole already checks for and installs docker, however it's meant to run a a Debian distro.
- You can expose WireGuard by exposing port 80 under the wg-dashboard service in your desired docker global config. Don't directly modify docker-compose.yml 
- the Master Key is for decrypting the master client config file. Is encrypted after generating the QR code.
- As for speed issues thats on your hardware mate.

Anyway im tired it's 8:45 over here. If the project helped you leave a star and if you're feeling generous here's my cashapp $N0XCIS.

Will update readme when I wake up.

**Comment by NOXCIS** [comment]
![image](https://github.com/NOXCIS/Worm-Hole/assets/26854391/c66d8b16-48ed-478f-b7fc-1877ae2ff0ed)
