### ISSUE TITLE
Wireguard peers disappear and interface turns off after restart

### ISSUE THREAD

**Issue by Kitmitsu** [NOXCIS/Worm-Hole#2]
I have Worm-Hole running on a fresh Debian VM with nothing else but it's dependencies. The settings I picked during setup were all the defaults. It works great, however each time either the wg_dashboard container is restarted or the entire VM is rebooted, the peer settings are wiped from wg0.conf. The interface settings themselves remain intact in the config file even after changing them and rebooting.

As well as that, after a restart the wg0 interface doesn't start until it's toggled on manually via the dashboard or command line.

Any clues how to fix this?

**Comment by NOXCIS** [comment]
Comment out this line in WG-Dash/entrypoint.sh if you want the config to stay after restart (rm /etc/wireguard/*.conf). I added it for dev purposes. I'm going to switch to different dashboard soon once integrate 2fa by Authnik.

**Comment by Kitmitsu** [comment]
I knew I missed something. Thanks!

**Comment by NOXCIS** [comment]
@Kitmitsu ive updated the image to auto start and added functionality for multiple auto starting interfaces
