### ISSUE TITLE
Improve ReadMe (Setup instructions)

### ISSUE THREAD

**Issue by Neotastisch** [NOXCIS/Worm-Hole#4]
.

**Comment by NOXCIS** [comment]
What are you having problems with

**Comment by Neotastisch** [comment]
Installation steps in the ReadMe would be great, i have no idea what to do

**Comment by NOXCIS** [comment]
git  clone -b nginx-++ https://github.com/NOXCIS/Worm-Hole.git
cd  Worm-Hole
chmod  +x  setup-headless.sh
sudo ./setup-headless.sh


Just run those commands
