### ISSUE TITLE
Change Upstream DNS from cloudflare 1.1.1.1 to 1.1.1.3 in Unbound

### ISSUE THREAD

**Issue by jan-dane** [NOXCIS/Worm-Hole#5]
Thanks for the proj.
How I can change Upstream DNS server from cloudflare 1.1.1.1 to 1.1.1.3 or any other DNS server in Unbound configuration.

**Comment by NOXCIS** [comment]
I added a custom unbound config that does that https://github.com/NOXCIS/Worm-Hole/blob/main/pi-hole.conf

**Comment by jan-dane** [comment]
> I added a custom unbound config that does that https://github.com/NOXCIS/Worm-Hole/blob/main/pi-hole.conf

Thx for the reply.....
but where i supposed to copy or insert the file????
where it has been referenced/copied or inserted in configuration????
please. elaborate..... sorry for my ignorance.....

**Comment by NOXCIS** [comment]
I updated the instructions to help make things a little clearer and set cloud flare to the default upstream dns for unbound.
