### ISSUE TITLE
WGDashboard available outside local network in headless mode

### ISSUE THREAD

**Issue by ronycage** [NOXCIS/Worm-Hole#8]
I can access WGDashboard outside network with default admin admin credentials.
This is potentially unsafe if You can access web panel outside local network.
I think it would be better if you could access web panel only if you connected to a peer like in wirehole.

I installed this docker image by your instructions on a clean Debian installation.
```bash
#!/bin/bash
git  clone  https://github.com/NOXCIS/Worm-Hole.git
cd  Worm-Hole
chmod  +x  install.sh
# I chose automatic install
sudo  ./install.sh
sudo docker-compose up
```

**Comment by ronycage** [comment]
Also I can't even enable wg0
![image](https://github.com/NOXCIS/Worm-Hole/assets/126236128/52f45ba5-7753-4a16-8d43-59bb6b55ea39)

**Comment by NOXCIS** [comment]
Fixes pushing tomorrow...

**Comment by NOXCIS** [comment]
@ronycage What is your setup btw?

**Comment by ronycage** [comment]
> @ronycage What is your setup btw?

 My setup is Debian 10 on a VPS, I'm updating to a 12 version right now

**Comment by NOXCIS** [comment]
Try latest pull
